### ISSUE TITLE
problems when running in VS

### ISSUE THREAD

**Issue by flieks** [paulvanbladel/aurelia-identityserver-aspnetcore#1]
Hi Paul, 

Thanks for great work. I'm trying to get it to work.

I followed your instructions:
All dnu restore/npm installs went OK.
only cd src/IdSvrConstants project is not in the solution/folder.

Then StartDNX.cmd gives error:
![image](https://cloud.githubusercontent.com/assets/5032389/14314111/b686f9ea-fbf5-11e5-84d6-ea0a33d997a2.png)
aldough i have the 1.0.0-rc1-update2 installed:
![image](https://cloud.githubusercontent.com/assets/5032389/14314385/21b57c4a-fbf7-11e5-96cc-6bffe72ac225.png)

So then i did "npm run build" or "npm run dev" , works fine. 
But when F5 on AureliaAspNetApp or AureliaWebsite gives:
Promise' is undefined
in bundle.js
![image](https://cloud.githubusercontent.com/assets/5032389/14314254/623c6356-fbf6-11e5-93d7-a66f6b6b9018.png)
i searched on gitter/google but can't find it (running in IISExpress, IE).

Thanks
Felix

**Comment by paulvanbladel** [comment]
Hi Felix,  
Good catch, dnx-watch needs to be installed
dnu commands install Microsoft.Dnx.Watcher
I updated readme

**Comment by flieks** [comment]
Thanks Paul, that fixed it.

Now i get another error on line
`_aureliaPal.DOM.injectStyles('.aurelia-hide { display:none !important; }');`

because in PAL beta.1.1.1, the injectStyles() doesn't exist anymore. (see [link](http://aurelia.io/docs.html#/aurelia/pal/1.0.0-beta.1.1.1/doc/api/overview))
I can't seem to find where you wrote this.. (outside the bundle)

**Comment by paulvanbladel** [comment]
Did you try npm dedupe ?

https://github.com/aurelia/skeleton-navigation/issues/348

**Comment by paulvanbladel** [comment]
Fixed? If not, feel free to reopen.
