### ISSUE TITLE
Query : 'Make sure you have a linux box at your disposal (DigitalOcean, Azure, VirtualBox, ...)'

### ISSUE THREAD

**Issue by MrChriZ** [paulvanbladel/aurelia-identityserver-aspnetcore#5]
Why do you need to do this when Docker can run on just about anything - Windows, Mac, Linux?

**Comment by MrChriZ** [comment]
Am I also right in thinking this sample you can either run with docker or without?  
If so I think the documentation could do with being clearer about this.

**Comment by paulvanbladel** [comment]
Hi,
In my understanding, everything that can run on docker can also run on linux.
Sure, if you want to run the sample on windows, you can just deploy on a web/application server.
